name:                ranged-list
version:             0.1.1.1
github:              "YoshikuniJujo/ranged-list"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: The list like structure whose length or range of length can be specified
category:            List

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/ranged-list#readme>

dependencies:
- base >= 4.7 && < 5
- typecheck-plugin-nat-simple

library:
  source-dirs: src
  exposed-modules:
  - Data.List.Length
  - Data.List.Range
  - Data.List.Range.Nat

tests:
  ranged-list-test:
    main:                spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ranged-list
  ranged-list-doctest:
    main:                doctests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ranged-list
    - doctest

data-dir: sample

data-files:
- rectangle.hs
- word64.hs
- LengthR.hs
- fourPointsOfRect.hs
- password.hs
- fingertree.hs
